version: '3.8'

services:
  backend:
    build: .
    # Backend should not expose ports directly in production behind NGINX
    # ports:
    #   - "8000:8000"
    env_file:
      - .env.prod  # use production env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/Backend/uploads
    working_dir: /Backend
    restart: unless-stopped
    command: >
      gunicorn -w 4 -k uvicorn.workers.UvicornWorker aetherium.main:app --bind 0.0.0.0:8000

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default-pro.conf:/etc/nginx/conf.d/default.conf
      - ./uploads:/Backend/uploads
      - /etc/letsencrypt:/etc/letsencrypt  
    depends_on:
      - backend
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery_worker:
    build: .
    command: >
      celery -A aetherium.utils.celery_worker worker --loglevel=info
      --queues=file_uploads,status_checks,emails,default
      --without-mingle --without-gossip
    env_file:
      - .env.prod
    depends_on:
      - backend
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
