
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.dev 
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/Backend/uploads
    working_dir: /Backend
    restart: unless-stopped
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./uploads:/Backend/uploads
    depends_on:
      - backend
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env.dev   
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro # optional
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery_worker:
    build: .
    command: >
      celery -A aetherium.utils.celery_worker worker --loglevel=info
      --queues=file_uploads,status_checks,emails,default
      --without-mingle --without-gossip
    env_file:
      - .env.dev
    depends_on:
      - backend
      - redis
    restart: unless-stopped

volumes:

  postgres_data:
