"""two_fields_added_to_lessonmodel

Revision ID: 2b3af57b5cc8
Revises: 52c374a8ffab
Create Date: 2025-07-08 11:56:11.072430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b3af57b5cc8'
down_revision: Union[str, None] = '52c374a8ffab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('content_data', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('order_index', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('assessment', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'assessment')
    op.drop_column('lessons', 'order_index')
    op.drop_column('lessons', 'content_data')
    # ### end Alembic commands ###
