"""three_tax_amount, subtotal, total_amount added to purchase_wallet and added to user

Revision ID: 646cddc343fd
Revises: fc0a53805f65
Create Date: 2025-07-18 01:21:59.450667

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646cddc343fd'
down_revision: Union[str, None] = 'fc0a53805f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('subtotal', sa.Float(), nullable=False))
    op.add_column('purchases', sa.Column('tax_amount', sa.Float(), nullable=False))
    op.add_column('purchases', sa.Column('total_amount', sa.Float(), nullable=False))

     # Create wallets table
    op.create_table(
        'wallets',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('balance', sa.Float(), nullable=False, server_default="0.0"),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP'))
    )

    # Create wallet_transactions table
    op.create_table(
        'wallet_transactions',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('wallet_id', sa.Integer(), sa.ForeignKey('wallets.id'), nullable=False),
        sa.Column('transaction_type', sa.String(length=20), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('reference_id', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP'))
    )

    # ### end Alembic commands ###


def downgrade() -> None:

    # Drop wallet_transactions table
    op.drop_table('wallet_transactions')

    # Drop wallets table
    op.drop_table('wallets')
    
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'total_amount')
    op.drop_column('purchases', 'tax_amount')
    op.drop_column('purchases', 'subtotal')
    # ### end Alembic commands ###
