"""constraint changes for the course table

Revision ID: 8959b87b9598
Revises: 709b853eb257
Create Date: 2025-06-20 15:21:42.951755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8959b87b9598'
down_revision: Union[str, None] = '709b853eb257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('courses', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'language',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('courses', 'level',
               existing_type=postgresql.ENUM('Beginner', 'Intermediate', 'Expert', 'All Levels', name='courselevel'),
               nullable=True)
    op.alter_column('courses', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'duration_unit',
               existing_type=postgresql.ENUM('hours', 'days', name='durationunit'),
               nullable=True)
    op.alter_column('courses', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('courses', 'duration_unit',
               existing_type=postgresql.ENUM('hours', 'days', name='durationunit'),
               nullable=False)
    op.alter_column('courses', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'level',
               existing_type=postgresql.ENUM('Beginner', 'Intermediate', 'Expert', 'All Levels', name='courselevel'),
               nullable=False)
    op.alter_column('courses', 'language',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('courses', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
