"""Add new user fields

Revision ID: c874cee95495
Revises: 1ed4008d1727
Create Date: 2025-06-10 23:51:16.701420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c874cee95495'
down_revision: Union[str, None] = '1ed4008d1727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True,unique=True))
    op.add_column('users', sa.Column('personal_website', sa.String(), nullable=True))
    op.add_column('users', sa.Column('facebook', sa.String(), nullable=True))
    op.add_column('users', sa.Column('instagram', sa.String(), nullable=True))
    op.add_column('users', sa.Column('linkedin', sa.String(), nullable=True))
    op.add_column('users', sa.Column('whatsapp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('youtube', sa.String(), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'youtube')
    op.drop_column('users', 'whatsapp')
    op.drop_column('users', 'linkedin')
    op.drop_column('users', 'instagram')
    op.drop_column('users', 'facebook')
    op.drop_column('users', 'personal_website')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
