"""change enum values to lowercase

Revision ID: dfb5a0dc5824
Revises: 095b0899c369
Create Date: 2025-06-19 19:37:17.450737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb5a0dc5824'
down_revision: Union[str, None] = '095b0899c369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE durationunit RENAME VALUE 'HOURS' TO 'hours'")
    op.execute("ALTER TYPE durationunit RENAME VALUE 'DAYS' TO 'days'")
    op.execute("ALTER TYPE verificationstatus RENAME VALUE 'PENDING' TO 'pending'")
    op.execute("ALTER TYPE verificationstatus RENAME VALUE 'VERIFIED' TO 'verified'")
    op.execute("ALTER TYPE verificationstatus RENAME VALUE 'REJECTED' TO 'rejected'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE durationunit RENAME VALUE 'hours' TO 'HOURS'")
    op.execute("ALTER TYPE durationunit RENAME VALUE 'days' TO 'DAYS'")
    op.execute("ALTER TYPE verificationstatus RENAME VALUE 'pending' TO 'PENDING'")
    op.execute("ALTER TYPE verificationstatus RENAME VALUE 'verified' TO 'VERIFIED'")
    op.execute("ALTER TYPE verificationstatus RENAME VALUE 'rejected' TO 'REJECTED'")
    # ### end Alembic commands ###
