""" added is_emailverified to users

Revision ID: ed9826bd43e0
Revises: ad1b4634f3b9
Create Date: 2025-06-09 10:41:13.781505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed9826bd43e0'
down_revision: Union[str, None] = 'ad1b4634f3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_emailverified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_emailverified')
    # ### end Alembic commands ###
