"""lesson comments tables

Revision ID: lesson_comments_migration
Revises: 634151053176
Create Date: 2025-01-27 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'lesson_comments_migration'
down_revision: Union[str, None] = '634151053176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create lesson_comments table
    op.create_table('lesson_comments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('lesson_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('parent_comment_id', sa.Integer(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('is_edited', sa.Boolean(), default=False),
        sa.Column('is_deleted', sa.Boolean(), default=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['parent_comment_id'], ['lesson_comments.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_comments_id'), 'lesson_comments', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_comments_lesson_id'), 'lesson_comments', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_comments_user_id'), 'lesson_comments', ['user_id'], unique=False)
    
    # Create lesson_comment_edits table
    op.create_table('lesson_comment_edits',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('comment_id', sa.Integer(), nullable=False),
        sa.Column('previous_content', sa.Text(), nullable=False),
        sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['comment_id'], ['lesson_comments.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_comment_edits_id'), 'lesson_comment_edits', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_comment_edits_comment_id'), 'lesson_comment_edits', ['comment_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_lesson_comment_edits_comment_id'), table_name='lesson_comment_edits')
    op.drop_index(op.f('ix_lesson_comment_edits_id'), table_name='lesson_comment_edits')
    op.drop_table('lesson_comment_edits')
    
    op.drop_index(op.f('ix_lesson_comments_user_id'), table_name='lesson_comments')
    op.drop_index(op.f('ix_lesson_comments_lesson_id'), table_name='lesson_comments')
    op.drop_index(op.f('ix_lesson_comments_id'), table_name='lesson_comments')
    op.drop_table('lesson_comments')
    
    # ### end Alembic commands ###



